### ISSUE TITLE
Description about how `pool.debug: true` works

### ISSUE THREAD

**Issue by gam6itko** [spiral/roadrunner-docs#128]
Please add clarification on how debug mode works.

Supposed place: https://roadrunner.dev/docs/php-developer/2.x/en#debug-mode

I have certain rr config
```yaml
jobs:
  pool:
    debug: true
    command: "php app.php"
    num_workers: 1
```

But if I push several jobs to queue I see that rr creates several parallel workers.

![image](https://user-images.githubusercontent.com/3841197/222213792-1fb8629b-fdff-4766-8b90-bd5adb7366f4.png)

**Comment by rustatian** [comment]
Done in the upcoming docs `v2023`
