### ISSUE TITLE
A link to nowhere

### ISSUE THREAD

**Issue by viktorprogger** [spiral/roadrunner-docs#49]
There is a link leading to "404 Not found" on the https://roadrunner.dev/docs/php-worker page. It's the last link on this page, "Workflow/Activity Worker".

**Comment by 48d90782** [comment]
@viktorprogger Nice catch, thanks. Fixed.

**Comment by 48d90782** [comment]
This is the correct link: https://docs.temporal.io/docs/php-workers/
