### ISSUE TITLE
Broken link on the Copy main.go file link.

### ISSUE THREAD

**Issue by litan1106** [spiral/roadrunner-docs#51]
Broken link on the Copy main.go file link.

https://github.com/spiral/roadrunner-binary/blob/main/main.go (not exists)

https://roadrunner.dev/docs/beep-beep-build
![image](https://user-images.githubusercontent.com/1310539/114247966-4ee29080-994b-11eb-94e1-bb460100b737.png)

**Comment by wolfy-j** [comment]
Fixed, thank you.

**Comment by litan1106** [comment]
Thanks. The following file screenshot didn't make sense. It might be outdated for Roadrunner v2.

I found the plugins in other file but not main.go

https://github.com/spiral/roadrunner-binary/blob/e6821d3496981e2d02f12c1659cbe86ee17f1b2f/internal/container/plugins.go#L21

**Comment by wolfy-j** [comment]
@48d90782 I think this task is for you. :)
@litan1106 thank you for the suggestion!

**Comment by 48d90782** [comment]
@litan1106 I've created a ticket https://github.com/spiral/roadrunner/issues/626, feel free to put your thoughts in it, which also you wanted to see in the repo with samples.
