### ISSUE TITLE
Update docs for status endpoints 

### ISSUE THREAD

**Issue by masterjus** [spiral/roadrunner-docs#89]
The current documentation a bit confusing because there's no explanation what is difference between `/health` endpoint and `/ready`.

Also it's good to know that if a request to these urls are wrong (wrong plugin name or even no `plugin` query param) you still receive a response with status code 200.

**Comment by rustatian** [comment]
done: https://github.com/spiral/roadrunner-docs/commit/d1d0a001aaa825d759b96d014234de218ff37554
